### ISSUE TITLE
1.1 Загрузка и чтение моделей

### ISSUE THREAD

**Issue by polyarnost** [corodod/KGProject#1]
Вместо сырого ObjReader должна быть качественная протестированная реализация: ваша или другого студента, если вы ее не делали в третьей задаче. А также должна быть возможность сохранения модели с помощью ObjWriter по кнопке в меню.

**Comment by Supremas1** [comment]
Готово.

**Comment by Supremas1** [comment]
не готова, что-то пошло не так
